### ISSUE TITLE
Working GovCloud example?

### ISSUE THREAD

**Issue by mfann-or** [aws-ia/terraform-aws-datasync#28]
Hi,

I've been trying to figure out how to use this module for cross-partition datasync from Commercial to GovCloud -- unsuccessfully.

I'm hoping someone might have a working example that I can learn from.

Thanks!

**Comment by harsheetas** [comment]
Thanks for the suggestion. Cross partition sync requires a EC2 DataSync agent. The Cross account S3 example is only intended for commercial partition. 

Here is a blog post that outlines the details : https://aws.amazon.com/blogs/storage/transferring-data-in-amazon-s3-between-aws-govcloud-us-regions-and-commercial-aws-regions-using-aws-datasync/

We will consider this as a possible road map item for this module.
